CREATE TABLE t_user_devices (
    f_device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    f_user_id INTEGER NOT NULL,
    f_fcm_token VARCHAR(512) NOT NULL UNIQUE,
    f_device_type VARCHAR(20),
    f_app_version VARCHAR(50),
    f_os_version VARCHAR(50),
    f_last_active_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    f_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_devices_user FOREIGN KEY (f_user_id) REFERENCES m_users (f_user_id) ON DELETE CASCADE
);

CREATE INDEX idx_user_devices_user_id ON t_user_devices (f_user_id);
