POST http://localhost:8080/api/items
Content-Type: application/json

{
  "name": "このんいちは",
  "price": 2500
}


### ユーザー登録
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password",
  "username": "wkm"
}





### ログイン状態にする
GET http://localhost:8080/api/users/me/theme
Authorization: Basic user password

### 登録されたアイテムを全件取得する
GET http://localhost:8080/api/items

### Get theme of user 1
GET http://localhost:8080/api/users/1/theme
Accept: application/json

### Update theme of user 1
PUT http://localhost:8080/api/users/1/theme
Content-Type: application/json

{
  "theme": "dark"
}

### Update theme of user 1 to light
PUT http://localhost:8080/api/users/1/theme
Content-Type: application/json

{
  "theme": "light"
}


curl -i -c cookies.txt -X POST http://localhost:8080/v1/auth/login \
  -H "Content-Type: application/json" \
  -d '{"username":"themeuser","password":"secret123"}'

curl -b cookies.txt -X PUT http://localhost:8080/api/users/me/theme \
  -H "Content-Type: application/json" \
  -d '{"theme":1}'
